version: "2"
plugins:
  pep8:
    enabled: true
  radon:
    enabled: true
    channel: beta
  markdownlint:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - project/**/tests.py

exclude_patterns:
  - "project/**/migrations/"
  - "project/**/tests.py"
