name: python

on:
  pull_request:
    branches: main

jobs:
  lint:
    name: "Lint and test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: python -m pip install --user poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Lint with isort
        run: poetry run isort . --check
      - name: Lint with black
        run: poetry run black . --check
      - name: Lint with flake8
        run: poetry run pflake8 .
      - name: Run tests
        run: poetry run python project/manage.py test
      - name: Generate test coverage report
        run: poetry run coverage run project/manage.py test project
      - name: Prepare test coverage repoirt for upload
        run: poetry run coverage xml
      - name: Upload test coverage report
        uses: codecov/codecov-action@v3
