name: python

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: python -m pip install --user poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Lint with isort
        run: poetry run isort . --check
      - name: Lint with black
        run: poetry run black . --check
      - name: Lint with flake8
        run: poetry run pflake8 .
      - name: Run tests
        run: python project/manage.py test
